subscription_id       = "de448de3-61e7-4067-b981-d1aeb0ce136d"
location              = "eastus2"
app_service_plan_name = "asp-tbc-app-services-01"
app_service_plan_rg   = "rg-tbc-app-services"
acs_name              = "TBC-Subscription-ACS"
acs_rg                = "RG-ACS-Email"
