#file: noinspection UndefinedAction
name: CI

on:
  pull_request:
    paths:
      - "pyproject.toml"
      - "uv.lock"
      - "src/**"
      - "tests/**"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Lint
        run: |
          uv run ruff check .
          uv run ruff format --check .

      - name: Type check
        run: uv run pyright

      - name: Test
        run: uv run pytest
